### ISSUE TITLE
UI Related Bugs in Sent Mail , Advanced Settings & Login Page

### ISSUE THREAD

**Issue by AkshatGupta15** [pclubiitk/IITK-Mail-Client#34]
## From is Written twice
<br/>

<div style="text-align: center;">
  <img src="https://github.com/pclubiitk/IITK-Mail-Client/assets/146257084/0738c529-1ed7-4281-9d38-3113e3c8c24b" width="150" />
</div>

<br/><br/>
## Not enough gap in advanced setting fields and label
<br/>
<img src="https://github.com/pclubiitk/IITK-Mail-Client/assets/146257084/51794a4e-4b46-4b2b-ad72-ef15b69ee6a8" width="150" />

<br/><br/>
## if possible make make appbar background same as body in login and lower the size of advance setting button
<br/>
<img src="https://github.com/pclubiitk/IITK-Mail-Client/assets/146257084/11b8d7fe-fb43-4f9a-8372-e469db1fc663" width="150" />

**Comment by bmerchant22** [comment]
I would say keep the advanced settings button below the username and password, and fix the other UI changes as mentioned

**Comment by karankk-05** [comment]
I can address these issues.

**Comment by AkshatGupta15** [comment]
> I can address these issues.

I was assigned this issue and have mostly completed the necessary changes. I will add the pull request shortly and then close the issue.

**Comment by AkshatGupta15** [comment]
## Changes Done
<div style="text-align: center;">
  <img src="https://github.com/pclubiitk/IITK-Mail-Client/assets/146257084/90fa0f5f-d353-4f4a-a020-361ce46d02b4" width="150" />

<div style="text-align: center;">
  <img src="https://github.com/pclubiitk/IITK-Mail-Client/assets/146257084/d0abf029-2fd5-4fbc-9431-e1462e76e6f5" width="150" />
</div>


</div>
<div style="text-align: center;">
  <img src="https://github.com/pclubiitk/IITK-Mail-Client/assets/146257084/480a15d7-e995-4c86-8362-f6cbe1bb7d42" width="150" />
</div>

**Comment by yashlm** [comment]
looks good
