### ISSUE TITLE
Compose Mail: Error - No Recepient Specified  while sending mail 

### ISSUE THREAD

**Issue by AkshatGupta15** [pclubiitk/IITK-Mail-Client#36]
When sending mail to anyone not in address book, it fails to send giving 

https://github.com/pclubiitk/IITK-Mail-Client/assets/146257084/3941b9f7-0dc4-4502-88cd-6b8f51337edb

**Comment by PrabhakarRaj0328** [comment]
I changed the UI of every page but looks like someone overwrote them with their commit. Please fetch the latest commit and make changes before sending a pr.

**Comment by PrabhakarRaj0328** [comment]
I fixed the UI issue
