### ISSUE TITLE
HTML content being displayed in the body of the mail

### ISSUE THREAD

**Issue by bmerchant22** [pclubiitk/IITK-Mail-Client#39]
![Screenshot from 2024-06-29 12-13-31](https://github.com/pclubiitk/IITK-Mail-Client/assets/121559173/0c58e6d3-9dd4-4ade-b966-442585e49e21)

HTML content is being displayed in the body in mail view page as well as in the preview of the mail in email list page

**Comment by bmerchant22** [comment]
@piyushsingal3 take this up

**Comment by PrabhakarRaj0328** [comment]
i just did it so should i send the pr?
