### ISSUE TITLE
Extra space in subject of some mails

### ISSUE THREAD

**Issue by bmerchant22** [pclubiitk/IITK-Mail-Client#40]
![Screenshot from 2024-06-29 12-12-01](https://github.com/pclubiitk/IITK-Mail-Client/assets/121559173/ffde2b78-cfd9-44c9-b92c-364c9436cb03)

In some of the mails in the mail list page, there is an extra space before the subject of the mail, as in the screenshot attached

**Comment by bmerchant22** [comment]
Ok, I got it, there is no extra space but the subject and initial part of the body are centered, so please left align them

**Comment by karankk-05** [comment]
I resolved it into the new PR
