### ISSUE TITLE
Recipient issue in compose email page

### ISSUE THREAD

**Issue by bmerchant22** [pclubiitk/IITK-Mail-Client#41]
https://github.com/pclubiitk/IITK-Mail-Client/assets/121559173/aed2470d-8b95-4de9-9e99-11a10f75a502

When sending mail, to add recipients, we need to press enter key, to have a better UX, you can have something like this as shown in the video, if the address is not in your address book, display "add recipient", and if it is in the address book, display the suggestion

**Comment by bmerchant22** [comment]
@Abhimanyu-dev take up this issue, comment on this issue and I'll assign you

**Comment by Abhimanyu-dev** [comment]
👍👍
