### ISSUE TITLE
UI on Desktop

### ISSUE THREAD

**Issue by bmerchant22** [pclubiitk/IITK-Mail-Client#42]
We need to have a conditional rendering based on the screen size, majorly in the email list page. It looks good on the phone, but on desktop, we need quite different UI. You can take inspiration from gmail for the same.

**Comment by KrishJain256** [comment]
i can start working on this

**Comment by bmerchant22** [comment]
> i can start working on this

I have assigned this issue to you, share the ss on the discord channel and then add the PR

**Comment by KrishJain256** [comment]
i will be done by today eod mostly

**Comment by KrishJain256** [comment]
@bmerchant22 I am done with the desktop UI ( width > height for now, so same UI is for tablets )
Can you check if these pages look proper so I can put a PR
![Screenshot from 2024-07-03 16-22-54](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/961495be-343a-425b-9583-80280bf9c730)
![Screenshot from 2024-07-03 16-25-03](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/1120f89e-f926-4e01-8451-63a9063cd243)
![Screenshot from 2024-07-03 16-25-30](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/205a8bf9-06f9-4ab3-b12d-07383c5ef98e)
![Screenshot from 2024-07-03 16-26-12](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/eaace8d8-6911-4535-ae88-80773ae21419)
![Screenshot from 2024-07-03 16-26-32](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/2e6fd6da-082c-4296-a23d-173dcdc6d357)
![Screenshot from 2024-07-03 16-26-47](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/aedfab5e-b2ab-4b29-9af2-ea8b538033c1)

**Comment by KrishJain256** [comment]
@bmerchant22 also, the attachment functionality isnt working. It gives the following error
![Screenshot from 2024-07-03 16-28-29](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/2a49397a-3e6b-4669-b592-57ef287cfe43)

**Comment by KrishJain256** [comment]
@bmerchant22 There is a slight change in the directory structure. I have created different files for the Desktop UI. We can choose to merge them too ( I kept it this way so to keep the code readable and short )
![Screenshot from 2024-07-03 16-31-04](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/0843d278-c737-4e6d-9e1c-15f41725e519)

**Comment by yashlm** [comment]
> @bmerchant22 I am done with the desktop UI ( width > height for now, so same UI is for tablets ) Can you check if these pages look proper so I can put a PR ![Screenshot from 2024-07-03 16-22-54](https://private-user-images.githubusercontent.com/138436914/345393019-961495be-343a-425b-9583-80280bf9c730.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMzA1MTAsIm5iZiI6MTcyMDEzMDIxMCwicGF0aCI6Ii8xMzg0MzY5MTQvMzQ1MzkzMDE5LTk2MTQ5NWJlLTM0M2EtNDI1Yi05NTgzLTgwMjgwYmY5YzczMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQyMTU2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTRiZjBkOTE0OGI2OTRhYjI1NWIwNWJhNzMxMDIzNDJhNjNmMDNiZjEyOTIzOTQzNTNjODhhYmEyNjQwYWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BedkR0cuP_9ohZ_Qguo9tPAWWA8dQQ4U6J5sXsgKeBU) ![Screenshot from 2024-07-03 16-25-03](https://private-user-images.githubusercontent.com/138436914/345393367-1120f89e-f926-4e01-8451-63a9063cd243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMzA1MTAsIm5iZiI6MTcyMDEzMDIxMCwicGF0aCI6Ii8xMzg0MzY5MTQvMzQ1MzkzMzY3LTExMjBmODllLWY5MjYtNGUwMS04NDUxLTYzYTkwNjNjZDI0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQyMTU2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWMxM2ZmZDQ4ZDA3NDkwNjhjZDRkMWMwOWJkNDFiN2E4NTE4NjZlYTgxZTVmMzlkZDBkNmYyZDM3MzEyM2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.afDHD0FvwzYdaQ98VHqdadMspIOG4SUdPgTz1-M3Hmo) ![Screenshot from 2024-07-03 16-25-30](https://private-user-images.githubusercontent.com/138436914/345393474-205a8bf9-06f9-4ab3-b12d-07383c5ef98e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMzA1MTAsIm5iZiI6MTcyMDEzMDIxMCwicGF0aCI6Ii8xMzg0MzY5MTQvMzQ1MzkzNDc0LTIwNWE4YmY5LTA2ZjktNGFiMy1iMTJkLTA3MzgzYzVlZjk4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQyMTU2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWM1NjA0NzdiM2I4YWMxOWYzMzIwMjk5YTI4MGQ1Nzc3MjJkMDcwZWZhOTdhZjE5YzFhOTZmMTMwMTI2ZmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BUuiOO2MKGPSakyiPQpBKwkH5CoS7icvkP7DiEg8N28) ![Screenshot from 2024-07-03 16-26-12](https://private-user-images.githubusercontent.com/138436914/345393709-eaace8d8-6911-4535-ae88-80773ae21419.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMzA1MTAsIm5iZiI6MTcyMDEzMDIxMCwicGF0aCI6Ii8xMzg0MzY5MTQvMzQ1MzkzNzA5LWVhYWNlOGQ4LTY5MTEtNDUzNS1hZTg4LTgwNzczYWUyMTQxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQyMTU2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTE1MGFmMzU4Mjc0OWYyMGExMjQ4Yjg5NDYzMGViMTVlYmY0MDk4MTZkMDFkMjgwZDdmOGEzNTk5NzlhY2FiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ui9iUsYja8hdxtWEls-eOiqiMOoDdCuSkb3eip_QCfc) ![Screenshot from 2024-07-03 16-26-32](https://private-user-images.githubusercontent.com/138436914/345393786-2e6fd6da-082c-4296-a23d-173dcdc6d357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMzA1MTAsIm5iZiI6MTcyMDEzMDIxMCwicGF0aCI6Ii8xMzg0MzY5MTQvMzQ1MzkzNzg2LTJlNmZkNmRhLTA4MmMtNDI5Ni1hMjNkLTE3M2RjZGM2ZDM1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQyMTU2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzY5Nzk4NDRiMWMxMWEzMjdlOGYxMzk2ZWJhZTEyZDlkNmE3Y2JiZTIzM2NjMDc3ZGQ3NzllZWMzMGM1OGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-DwkygfcEyIbOP-w2Em3HuC38aZOeNlXgdlQK4Oz7u8) ![Screenshot from 2024-07-03 16-26-47](https://private-user-images.githubusercontent.com/138436914/345393854-aedfab5e-b2ab-4b29-9af2-ea8b538033c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMzA1MTAsIm5iZiI6MTcyMDEzMDIxMCwicGF0aCI6Ii8xMzg0MzY5MTQvMzQ1MzkzODU0LWFlZGZhYjVlLWIyYWItNGIyOS05YWYyLWVhOGI1MzgwMzNjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQyMTU2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmY3ZWU4YmI2ZjUwMGM5YjljMmQ1MTZmN2M3NDc0NzZmNzVjZDQyNjYyYmQyYTU4Y2JmNzhhM2Y3ODIxMzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZbuTxg_xtYXrZMlIBUTXUwPYsmqBz7CQWqdzB9oOlGk)

you can keep the drawer tabs like the inbox, sent, trash on display permanently...like its there in the webmail....you can also reduce the width of the list where it shows all the mails to make it look more compact...you can make the design the rest of the things similar to webmail as well

**Comment by yashlm** [comment]
> @bmerchant22 There is a slight change in the directory structure. I have created different files for the Desktop UI. We can choose to merge them too ( I kept it this way so to keep the code readable and short ) ![Screenshot from 2024-07-03 16-31-04](https://private-user-images.githubusercontent.com/138436914/345395088-0843d278-c737-4e6d-9e1c-15f41725e519.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMzA1MTAsIm5iZiI6MTcyMDEzMDIxMCwicGF0aCI6Ii8xMzg0MzY5MTQvMzQ1Mzk1MDg4LTA4NDNkMjc4LWM3MzctNGU2ZC05ZTFjLTE1ZjQxNzI1ZTUxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQyMTU2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjVhNGRlZDQzOTgzM2VmNDM1MjU0MzA0MmFkOGRkZjNlYmY3MzhmNGMwMTYxZGY3YTNiZTg5YTQyY2Y5NDkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ByW3bG7d1hqgXaX3stIh-SmVCEkgA42uF3B45h-sKXw)

it's better to keep them separate..so its fine

**Comment by KrishJain256** [comment]
@yashlm Also, do i make the drawer tabs permanent for only the desktop screen ( and not the tablets ).

**Comment by yashlm** [comment]
> @yashlm Also, do i make the drawer tabs permanent for only the desktop screen ( and not the tablets ).
> 

yes

**Comment by KrishJain256** [comment]
@yashlm done with the separate Desktop UI. I haven't applied the permanent drawer on the Advanced Settings page. The Tablet UI does not have a permanent drawer. Also, the attachment error has been resolved now.
![Screenshot from 2024-07-05 17-17-22](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/9db8b0ff-a0f8-4974-973f-3eda5df75b8f)
![Screenshot from 2024-07-05 17-18-57](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/abb11f12-d2ec-4c34-b6f3-fbd0310da7b5)
![Screenshot from 2024-07-05 17-19-19](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/69fb8fdc-e88e-409f-8723-e6b78b5c12fc)
![Screenshot from 2024-07-05 17-19-50](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/f90dfdba-54b4-4759-b0f4-818dd490645a)

**Comment by KrishJain256** [comment]
@yashlm The desktop files are also separated from the tablet ones causing a similar change in the directory structure as last time
Do I put a PR ?

**Comment by yashlm** [comment]
> @yashlm done with the separate Desktop UI. I haven't applied the permanent drawer on the Advanced Settings page. The Tablet UI does not have a permanent drawer. Also, the attachment error has been resolved now. ![Screenshot from 2024-07-05 17-17-22](https://private-user-images.githubusercontent.com/138436914/346114704-9db8b0ff-a0f8-4974-973f-3eda5df75b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTcxMTcsIm5iZiI6MTcyMDE5NjgxNywicGF0aCI6Ii8xMzg0MzY5MTQvMzQ2MTE0NzA0LTlkYjhiMGZmLWEwZjgtNDk3NC05NzNmLTNlZGE1ZGY3NWI4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNjI2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjE0M2M5ZmM0MTFlYjk0M2ZmOGJjMzVkNDYwZTQ0Mjc4YTE5NjgyMWJjNDNlMmY4MjUwNjUyNGYwNzdjYWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fb4iL89uPY0HCcVfeNVyUZanrVLdq_OXST284LtHuiY) ![Screenshot from 2024-07-05 17-18-57](https://private-user-images.githubusercontent.com/138436914/346114715-abb11f12-d2ec-4c34-b6f3-fbd0310da7b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTcxMTcsIm5iZiI6MTcyMDE5NjgxNywicGF0aCI6Ii8xMzg0MzY5MTQvMzQ2MTE0NzE1LWFiYjExZjEyLWQyZWMtNGMzNC1iNmYzLWZiZDAzMTBkYTdiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNjI2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjkyZjBkNTA1OGVmNmVkMTYxYmFmNmI2ZTNmZjRhZjllMzVlYjZiZTZjNmNkOWVhOGNlYjdjMTE3MzkxYmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jBmYFVXbQh07QQgPUGHmthJeL-IQTrrOj8OfQVCQa-c) ![Screenshot from 2024-07-05 17-19-19](https://private-user-images.githubusercontent.com/138436914/346114726-69fb8fdc-e88e-409f-8723-e6b78b5c12fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTcxMTcsIm5iZiI6MTcyMDE5NjgxNywicGF0aCI6Ii8xMzg0MzY5MTQvMzQ2MTE0NzI2LTY5ZmI4ZmRjLWU4OGUtNDA5Zi04NzIzLWU2Yjc4YjVjMTJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNjI2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODE4NTBhMDE2NGJiYzlkNDBkMDkyYTcxYjBmNTU3ODVlNTRkN2VjZGI4NjU5OGU0MTFiN2FkZTA2YzAyNmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SASDTvWK-jXJUPCnbMyEKqyAE9kcZ7jiZG99oDZEFDw) ![Screenshot from 2024-07-05 17-19-50](https://private-user-images.githubusercontent.com/138436914/346114739-f90dfdba-54b4-4759-b0f4-818dd490645a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTcxMTcsIm5iZiI6MTcyMDE5NjgxNywicGF0aCI6Ii8xMzg0MzY5MTQvMzQ2MTE0NzM5LWY5MGRmZGJhLTU0YjQtNDc1OS1iMGY0LTgxOGRkNDkwNjQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNjI2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGFkNTA0ODdjMzYzNTMwOTM3MjFjOWE0ZGQ1OWEyOTllZTJmMDQyYWViODQ3YWQzOTUzMDRhOTViZjUyYTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.frmP2fwso71MbIh5QR-ojiP-fsyRcYjnZEhgZtSYGdE)

implement it in advance settings as well...the application will seem more consistent that way...apart from this...the file structure and the other things seems good...you can put a pr

**Comment by KrishJain256** [comment]
Done :+1:
