### ISSUE TITLE
The attachment functionality isnt working. It gives the following error

### ISSUE THREAD

**Issue by yashlm** [pclubiitk/IITK-Mail-Client#50]
The attachment functionality isnt working. It gives the following error
![Screenshot from 2024-07-03 16-28-29](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/2a49397a-3e6b-4669-b592-57ef287cfe43)

_Originally posted by @KrishJain256 in https://github.com/pclubiitk/IITK-Mail-Client/issues/42#issuecomment-2205798566_

**Comment by yashlm** [comment]
@AdarshRaj241408 look into this and take up this issue

**Comment by KrishJain256** [comment]
@yashlm Fixed it ! Please close the issue

**Comment by KrishJain256** [comment]
@yashlm done with the separate Desktop UI. I haven't applied the permanent drawer on the Advanced Settings page. The Tablet UI does not have a permanent drawer. Also, the attachment error has been resolved now.
![Screenshot from 2024-07-05 17-17-22](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/4bc34734-0ee3-4305-a318-bba9b1a1df25)
![Screenshot from 2024-07-05 17-18-57](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/cbc66560-90f1-4b68-989a-150cb7af868c)
![Screenshot from 2024-07-05 17-19-19](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/dac9c11c-c9bd-4cfe-809c-c55729e1452f)
![Screenshot from 2024-07-05 17-19-50](https://github.com/pclubiitk/IITK-Mail-Client/assets/138436914/85b1377c-b589-462b-b5d0-55efba671abe)
