### ISSUE TITLE
Flagged mails body shows HTML code 

### ISSUE THREAD

**Issue by hardik1408** [pclubiitk/IITK-Mail-Client#71]
![WhatsApp Image 2024-07-27 at 12 06 25_f0af2a99](https://github.com/user-attachments/assets/f30291dc-d13a-4f9f-8409-436d057edfe3)

**Comment by yashlm** [comment]
@piyushsingal3 look into this as well

**Comment by AkshatGupta15** [comment]
Fixed 
![Simulator Screenshot - iPhone 15 Pro - 2024-08-02 at 01 39 51](https://github.com/user-attachments/assets/43f87aa0-a013-4520-a996-5d14f914c655)
